export const Permissions = {
  ORG_READ: 'org:read',
  ORG_UPDATE: 'org:update',
  ORG_DELETE: 'org:delete',
  ORG_MANAGE_USERS: 'org:manage_users',
  ORG_MANAGE_INVITES: 'org:manage_invites',
  ORG_MANAGE_SUBSCRIPTION: 'org:manage_subscription',

  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',

  COURSES_READ: 'courses:read',
  COURSES_CREATE: 'courses:create',
  COURSES_UPDATE: 'courses:update',
  COURSES_DELETE: 'courses:delete',
  COURSES_PUBLISH: 'courses:publish',
  COURSES_ENROLL: 'courses:enroll',

  MODULES_CREATE: 'modules:create',
  MODULES_UPDATE: 'modules:update',
  MODULES_DELETE: 'modules:delete',

  LESSONS_CREATE: 'lessons:create',
  LESSONS_UPDATE: 'lessons:update',
  LESSONS_DELETE: 'lessons:delete',

  MEDIA_UPLOAD: 'media:upload',
  MEDIA_READ: 'media:read',
  MEDIA_DELETE: 'media:delete',

  QUIZZES_CREATE: 'quizzes:create',
  QUIZZES_UPDATE: 'quizzes:update',
  QUIZZES_DELETE: 'quizzes:delete',
  QUIZZES_ATTEMPT: 'quizzes:attempt',

  ANALYTICS_READ: 'analytics:read',
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
  AUDIT_READ: 'audit:read',
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_REFUND: 'payments:refund',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const RolePermissions: Record<string, Permission[]> = {
  PLATFORM_SUPER_ADMIN: Object.values(Permissions),
  ORGANIZATION_OWNER: [
    Permissions.ORG_READ,
    Permissions.ORG_UPDATE,
    Permissions.ORG_DELETE,
    Permissions.ORG_MANAGE_USERS,
    Permissions.ORG_MANAGE_INVITES,
    Permissions.ORG_MANAGE_SUBSCRIPTION,
    Permissions.USERS_READ,
    Permissions.USERS_CREATE,
    Permissions.USERS_UPDATE,
    Permissions.USERS_DELETE,
    Permissions.COURSES_READ,
    Permissions.COURSES_CREATE,
    Permissions.COURSES_UPDATE,
    Permissions.COURSES_DELETE,
    Permissions.COURSES_PUBLISH,
    Permissions.MODULES_CREATE,
    Permissions.MODULES_UPDATE,
    Permissions.MODULES_DELETE,
    Permissions.LESSONS_CREATE,
    Permissions.LESSONS_UPDATE,
    Permissions.LESSONS_DELETE,
    Permissions.MEDIA_UPLOAD,
    Permissions.MEDIA_READ,
    Permissions.MEDIA_DELETE,
    Permissions.QUIZZES_CREATE,
    Permissions.QUIZZES_UPDATE,
    Permissions.QUIZZES_DELETE,
    Permissions.ANALYTICS_READ,
    Permissions.SETTINGS_READ,
    Permissions.SETTINGS_UPDATE,
    Permissions.AUDIT_READ,
    Permissions.PAYMENTS_READ,
    Permissions.PAYMENTS_REFUND,
  ],
  ORGANIZATION_ADMIN: [
    Permissions.ORG_READ,
    Permissions.ORG_MANAGE_USERS,
    Permissions.ORG_MANAGE_INVITES,
    Permissions.USERS_READ,
    Permissions.USERS_CREATE,
    Permissions.USERS_UPDATE,
    Permissions.COURSES_READ,
    Permissions.COURSES_CREATE,
    Permissions.COURSES_UPDATE,
    Permissions.COURSES_DELETE,
    Permissions.COURSES_PUBLISH,
    Permissions.MODULES_CREATE,
    Permissions.MODULES_UPDATE,
    Permissions.MODULES_DELETE,
    Permissions.LESSONS_CREATE,
    Permissions.LESSONS_UPDATE,
    Permissions.LESSONS_DELETE,
    Permissions.MEDIA_UPLOAD,
    Permissions.MEDIA_READ,
    Permissions.MEDIA_DELETE,
    Permissions.QUIZZES_CREATE,
    Permissions.QUIZZES_UPDATE,
    Permissions.QUIZZES_DELETE,
    Permissions.ANALYTICS_READ,
    Permissions.SETTINGS_READ,
    Permissions.SETTINGS_UPDATE,
    Permissions.AUDIT_READ,
    Permissions.PAYMENTS_READ,
    Permissions.PAYMENTS_REFUND,
  ],
  TRAINER: [
    Permissions.ORG_READ,
    Permissions.USERS_READ,
    Permissions.COURSES_READ,
    Permissions.COURSES_CREATE,
    Permissions.COURSES_UPDATE,
    Permissions.MODULES_CREATE,
    Permissions.MODULES_UPDATE,
    Permissions.MODULES_DELETE,
    Permissions.LESSONS_CREATE,
    Permissions.LESSONS_UPDATE,
    Permissions.LESSONS_DELETE,
    Permissions.MEDIA_UPLOAD,
    Permissions.MEDIA_READ,
    Permissions.QUIZZES_CREATE,
    Permissions.QUIZZES_UPDATE,
    Permissions.QUIZZES_DELETE,
    Permissions.QUIZZES_ATTEMPT,
    Permissions.COURSES_ENROLL,
  ],
  TEACHING_ASSISTANT: [
    Permissions.ORG_READ,
    Permissions.USERS_READ,
    Permissions.COURSES_READ,
    Permissions.LESSONS_UPDATE,
    Permissions.MEDIA_READ,
    Permissions.QUIZZES_ATTEMPT,
    Permissions.COURSES_ENROLL,
  ],
  LEARNER: [
    Permissions.ORG_READ,
    Permissions.COURSES_READ,
    Permissions.COURSES_ENROLL,
    Permissions.QUIZZES_ATTEMPT,
  ],
};
